In [1]:
import pandas as pd

In [2]:
df = pd.read_excel("dados/futebol.xlsx")
df

,Times,Partidas_Jogadas,Vitorias,Empates,Derrotas,Gols_Pro,Gols_Contra,Saldo de gols,Pontos
0,Flamengo,10,7,2,1,22,10,12,23
1,São Paulo,10,6,1,3,16,15,1,19
2,Palmeiras,10,5,3,2,18,12,6,18
3,Santos,10,4,3,3,14,16,-2,15
4,Corinthians,10,3,2,5,10,20,-10,11

In [4]:
df.dtypes

Times               object
Partidas_Jogadas     int64
Vitorias             int64
Empates              int64
Derrotas             int64
Gols_Pro             int64
Gols_Contra          int64
Saldo de gols        int64
Pontos               int64
dtype: object

In [ ]:
df.describe()

<bound method NDFrame.describe of          Times  Partidas_Jogadas  Vitorias  Empates  Derrotas  Gols_Pro  \
0     Flamengo                10         7        2         1        22
1    São Paulo                10         6        1         3        16
2    Palmeiras                10         5        3         2        18
3       Santos                10         4        3         3        14
4  Corinthians                10         3        2         5        10

   Gols_Contra  Saldo de gols  Pontos
0           10             12      23
1           15              1      19
2           12              6      18
3           16             -2      15
4           20            -10      11  >

In [6]:
df.head(3)

,Times,Partidas_Jogadas,Vitorias,Empates,Derrotas,Gols_Pro,Gols_Contra,Saldo de gols,Pontos
0,Flamengo,10,7,2,1,22,10,12,23
1,São Paulo,10,6,1,3,16,15,1,19
2,Palmeiras,10,5,3,2,18,12,6,18

In [8]:
df.tail(2)

,Times,Partidas_Jogadas,Vitorias,Empates,Derrotas,Gols_Pro,Gols_Contra,Saldo de gols,Pontos
3,Santos,10,4,3,3,14,16,-2,15
4,Corinthians,10,3,2,5,10,20,-10,11

In [28]:
# Análise de desempenho por time:

desempenho = df[["Times", "Pontos", "Vitorias", "Saldo de gols"]].set_index("Times")
desempenho

             Pontos  Vitorias  Saldo de gols
Times
Flamengo         23         7             12
São Paulo        19         6              1
Palmeiras        18         5              6
Santos           15         4             -2
Corinthians      11         3            -10