In [5]:
import pandas as pd

In [6]:
data = {
    "Produto" : ["Arroz", "Feijão", "Abacate"],
    "Quantidade" : [23, 47, 19],
    "Preço" : [5.00, 6.40, 9.75]
}

df = pd.DataFrame(data)

In [7]:
df

   Produto  Quantidade  Preço
0    Arroz          23   5.00
1   Feijão          47   6.40
2  Abacate          19   9.75

In [11]:
df["Total"] = df["Quantidade"] * df["Preço"]

In [13]:
df

   Produto  Quantidade  Preço   Total
0    Arroz          23   5.00  115.00
1   Feijão          47   6.40  300.80
2  Abacate          19   9.75  185.25