In [19]:
import pandas as pd

In [20]:
data = {
    "Nome" : ["Ana", "Yan", "Rai"],
    "Idade" : [31,24,27],
    "Cidade" : ["São Paulo", "Manaus", "Porto Velho"]
}

In [21]:
type(data)

dict

In [22]:
dataTranslate = pd.DataFrame(data)

In [23]:
dataTranslate

  Nome  Idade       Cidade
0  Ana     31    São Paulo
1  Yan     24       Manaus
2  Rai     27  Porto Velho

In [26]:
dataTranslate.head(1)

  Nome  Idade     Cidade
0  Ana     31  São Paulo

In [27]:
dataTranslate.tail(2)

  Nome  Idade       Cidade
1  Yan     24       Manaus
2  Rai     27  Porto Velho

In [32]:
dados_notas = {
    'Nome': ['Ana', 'Caio', 'Cesar', 'David', 'Eva'],
    'Matemática': [85, 90, 78, 88, 92],
    'Física': [80, 75, 88, 85, 95],
    'Química': [78, 82, 85, 80, 88]
}

In [33]:
new_dados_notas = pd.DataFrame(dados_notas)
new_dados_notas

    Nome  Matemática  Física  Química
0    Ana          85      80       78
1   Caio          90      75       82
2  Cesar          78      88       85
3  David          88      85       80
4    Eva          92      95       88

In [35]:
# Calculando a média das notas:

new_dados_notas["Média"] = new_dados_notas[["Matemática", "Física", "Química"]].mean(axis=1)
new_dados_notas

    Nome  Matemática  Física  Química      Média
0    Ana          85      80       78  81.000000
1   Caio          90      75       82  82.333333
2  Cesar          78      88       85  83.666667
3  David          88      85       80  84.333333
4    Eva          92      95       88  91.666667

In [37]:
# Alunos com média maior que 82.5:

alunos_aprovados = new_dados_notas[new_dados_notas["Média"] >= 82.5]
alunos_aprovados

    Nome  Matemática  Física  Química      Média
2  Cesar          78      88       85  83.666667
3  David          88      85       80  84.333333
4    Eva          92      95       88  91.666667

In [40]:
# Média dos alunos aprovados:

new_dados_notas[["Nome", "Média"]]

    Nome      Média
0    Ana  81.000000
1   Caio  82.333333
2  Cesar  83.666667
3  David  84.333333
4    Eva  91.666667