In [15]:
import pandas as pd

In [17]:
vendas = {
    'Produto': ['Camisa', 'Calça', 'Saia', 'Camisa', 'Calça', 'Saia', 'Camiseta', 'Calça', 'Saia'],
    'Preço': [50, 100, 80, 55, 110, 85, 45, 95, 90],
    'Quantidade': [10, 15, 20, 5, 10, 15, 30, 20, 10],
    'Mês': ['Jan', 'Jan', 'Jan', 'Fev', 'Fev', 'Fev', 'Mar', 'Mar', 'Mar']
}

In [20]:
vendas_DataFrame = pd.DataFrame(vendas)
vendas_DataFrame

    Produto  Preço  Quantidade  Mês
0    Camisa     50          10  Jan
1     Calça    100          15  Jan
2      Saia     80          20  Jan
3    Camisa     55           5  Fev
4     Calça    110          10  Fev
5      Saia     85          15  Fev
6  Camiseta     45          30  Mar
7     Calça     95          20  Mar
8      Saia     90          10  Mar

In [ ]:
# Calculando a receita total:

vendas_DataFrame["Receita"] = vendas_DataFrame["Preço"] * vendas_DataFrame["Quantidade"]
vendas_DataFrame

    Produto  Preço  Quantidade  Mês  Receita
0    Camisa     50          10  Jan      500
1     Calça    100          15  Jan     1500
2      Saia     80          20  Jan     1600
3    Camisa     55           5  Fev      275
4     Calça    110          10  Fev     1100
5      Saia     85          15  Fev     1275
6  Camiseta     45          30  Mar     1350
7     Calça     95          20  Mar     1900
8      Saia     90          10  Mar      900

In [ ]:
# Sumarizando a receita do produto:

agrupamento = vendas_DataFrame.groupby("Produto")["Receita"].sum().reset_index()
agrupamento

    Produto  Receita
0     Calça     4500
1    Camisa      775
2  Camiseta     1350
3      Saia     3775