In [1]:
import pandas as pd
import matplotlib.pyplot as ptl

In [2]:
data = {
    'Nome': ['Alice', 'Bob', 'Charlie', 'David', 'Emily'],
    'Idade': [25, 30, 35, 40, 27],
    'Cargo': ['Analista', 'Gerente', 'CEO', 'Analista', 'Coordenador'],
    'Salario': [5000, 8000, 15000, 4800, 6000]
}

In [3]:
df = pd.DataFrame(data)
df

      Nome  Idade        Cargo  Salario
0    Alice     25     Analista     5000
1      Bob     30      Gerente     8000
2  Charlie     35          CEO    15000
3    David     40     Analista     4800
4    Emily     27  Coordenador     6000

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Nome     5 non-null      object
 1   Idade    5 non-null      int64
 2   Cargo    5 non-null      object
 3   Salario  5 non-null      int64
dtypes: int64(2), object(2)
memory usage: 288.0+ bytes

In [5]:
df.describe()

           Idade       Salario
count   5.000000      5.000000
mean   31.400000   7760.000000
std     6.107373   4241.226238
min    25.000000   4800.000000
25%    27.000000   5000.000000
50%    30.000000   6000.000000
75%    35.000000   8000.000000
max    40.000000  15000.000000

In [6]:
df[df["Salario"] > 5000]

      Nome  Idade        Cargo  Salario
1      Bob     30      Gerente     8000
2  Charlie     35          CEO    15000
4    Emily     27  Coordenador     6000

In [9]:
df.sort_values(by="Idade", ascending=True)

      Nome  Idade        Cargo  Salario
0    Alice     25     Analista     5000
4    Emily     27  Coordenador     6000
1      Bob     30      Gerente     8000
2  Charlie     35          CEO    15000
3    David     40     Analista     4800

In [10]:
df["Bonus"] = df["Salario"] * 0.1
df

      Nome  Idade        Cargo  Salario   Bonus
0    Alice     25     Analista     5000   500.0
1      Bob     30      Gerente     8000   800.0
2  Charlie     35          CEO    15000  1500.0
3    David     40     Analista     4800   480.0
4    Emily     27  Coordenador     6000   600.0

In [11]:
df.groupby("Cargo")["Salario"].mean()

Cargo
Analista        4900.0
CEO            15000.0
Coordenador     6000.0
Gerente         8000.0
Name: Salario, dtype: float64

In [ ]:
df.plot(
    kind="bar", 
    x="Nome",
    y="Salario",
    title="Salário dos funcionários",
    rot=45
)

KeyError: 'Salário'